---
title: "First Knit"
author: "Eden Williams"
output: 
  html_document:
    number_sections: true
    toc: true
    toc_depth: 5
date: "`r Sys.Date()`"   
---

# A Little Survey

Here are just a few questions so I can get to know you and so you can get practice submitting an assignment in Canvas.  For each question, insert your answer underneath. Make sure each answer is at the minimum a complete sentence with correctly spelled words and correct punctuation. 

## A short history of you.  
Where did you attend High School, and did you graduate? Compare English class to math, is one easier for you than the other? Finally which subject did you do the best in? Your answer should have at least two sentences devoted to each question.  
  
### my answer     
I attended Quartz Hill High School and I graduated from there in 2016. I've always been pretty good at English. Math on the other hand has always been kind of a struggle for me. My best subjects in high school were English and Art History. I've always prefered classes that allowed room for some sort of creativity.
     


## Your computer and your and its capability?  
 For this class  you need a computer you can use at home.  So, what kind is it (windows, Apple, Linux)?  On a scale of 1 to 10, where 1 is a total dummy (doesn't know a mouse from a keyboard) and 10 is a complete geek (knows computer stuff in and out) How do you rate yourself?  You also need to have have internet access. How is your connection to the internet where you live?

### my answer   
I have a an HP laptop that runs windows. I would rate my computer knowledge at a 7. I'm not a complete wiz but I definitely know my way around a computer.I have pretty decent internet connection at my house. My room is a deadzone so I usually just end up doing my homework in the living room, which is pretty reliable.
   

## Others and You?   
What name do you prefer to be called by your classmates and instructor, if your buddys call you something but you want people in the class to call you something else - what would that be? 

### my answer     
I prefered to be called by my name which is Eden. My homies call me E but calling me Eden is fine.
   
 




## Aspirations?   
What do you want to achieve in life?  What college subject do you think would be of the greatest interest to you? What degree or certificate are you trying to achieve?

### my answer     
I want to achieve a happy life filled with meaning and purpose. I want to be well traveled and well educated.Even though they don't pertain to my major I find a lot of sociology classes pretty interesting. I am currently majoring in Video Production and Design to transfer to a four year university and would one day like to own my own video company. 
   
 




## Past adventures?  
Have you ever gone to foreign countries, if so which ones, if not Where might you go in the future?  Have you ever been in the military, if so which branch, if not which branch would you choose if you got drafted, and why?

### my answer     
I have not been to any foreign countries but I would love to go to Berlin, The Netherlands, Italy, Japan, and France. I am not in the military and I would not join any branch of the military. No offense to any veterans.
  




## Why are you taking Statistics?  
Did you take Math 115 or Math 116 ?  Did you know Math 115 only satisfies a general education requirement but that Math 116 counts as taking statistics in several transfer institutions??  
What grade do you need to attain in stats to not upset your future plans, What is your plan?  
 

### my answer     
I am currently taking Math115 and it is the only statistics class I am taking. I did not know Math116 counts for transfer but considering my major I don't think it is necessary to take. In order to not upset my future plans, I just need to pass although I would like to get an A just for my own satisfaction. 
   
 






  




